= mibl - tools for meta-programming OCaml builds
:toc: auto
:toclevels: 3

Scheme tools for herding OCaml projects; in particular analyzing and
transforming link:https://dune.readthedocs.io/en/latest/[Dune],
link:https://opam.ocaml.org/doc/Manual.html[OPAM], and findlib
link:http://projects.camlcity.org/projects/dl/findlib-1.9.4/doc/ref-html/r759.html[META]
files.

If you prefer acronyms: **M**eta-**ibl**
("ibl" is Arabic for "camel"). Or _muta'ibbil_,  متئبّل . If you prefer recursion: **M**ibl **i**ntegrates
**b**uild **l**anguages.

IMPORTANT: **STATUS**: Alpha

`mibl` is derived from
link:https://ccrma.stanford.edu/software/snd/snd/s7.html[s7]. See
link:https://iainctduncan.github.io/scheme-for-max-docs/s7.html[Why S7
Scheme?] for reasons why.

== Using mibl

Normally mibl would be included as a dependency of a "mibl
application"; for example,
link:https://github.com/obazl/tools_obazl[tools-obazl] supports a
command, `bazel run @obazl//convert`, that uses mibl to convert Dune
projects to OBazl projects. But mibl commands can also be run directly.

[source,starlark, title="WORKSPACE.bazel"]
----
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
    name = "mibl",
    remote = "https://github.com/obazl/mibl",
    branch = ... see below ...
)
----

Branches;

* `main` should not be used until version 1 is released.
* `alpha` should usually work but is unstable. I push to the alpha
  branch when I have a set of changes in the dev branch that seem to
  work and have been at least lightly tested on MacOS and Linux.
* `dev` is where ongoing work happens. Very unstable.


== Principles of Operation

mibl is an engine and a language.

The engine crawls the source tree and constructs a "parsetree" data
structure (in Scheme syntax) representing the source tree but
structured to reflect Dune and OCaml semantics. For example it
pairs .ml and .mli files having the same stemname, and it embeds the
content of dunefiles into the parsetree. This part of mibl is written
in C. It passes the parsetree to the mibl application, which
"normalizes" it by for example resolving `deps` fields in `rule`
stanzas. The mibl application is written in s7 Scheme.

The resulting normalized data structure has (or should have) all the
information needed to generated build descriptions. The original
purpose was to generate BUILD.bazel files from Dune files, but care
has been taken to eliminate (or at least minimize) Bazel-dependent
features in the mibl data schema, so that uses can write emitters for
other build metalanguages (e.g. ninja).

== mibl commands

* `@mibl//mibl` - the engine. With `--main <script filename>` runs a script; otherwise launches a repl.

Aliases:

* `@mibl//emit:mibl` - runs `@mibl//mibl -- --main mibl_main.scm --emit-mibl`

Emits `.mibl/PROJECT.mibl` and `.mibl/PROJECT.s7`.

To also emit the parsetree:  `bazel run @mibl//emit:mibl -- --emit-parsetree`

* `@mibl//emit:parsetree` - runs `@mibl//mibl -- --main mibl_main.scm --emit-parsetree --halt-after parsetree

To print the parsetree or project mibl to the terminal, add `--show-parsetree` and `--show-mibl`, respectively.

=== @mibl//

== Running mibl in a Bazel environment

From within a Bazel project:

[source,shell]
----
$ bazel run @mibl//repl
----

Options: `-v` (verbose) and `-d` (mibl_debug).

Once in the repl, run `mibl-load-project` to crawl your project and produce a
hash-table of package specs:

[source,scheme]
----
(mibl-load-project "src/lib_stdlib_unix")
----

By default, `mibl-load-project` will interpret a single string arg as a file
path relative to the launch directory. You can also give it a list of
directories to crawl:

[source,scheme]
----
(mibl-load-project '("src/a" "src/b"))
----


You can also pass it two arguments: a path and a list of paths; the
first will be interpreted as a path relative to your `$HOME`
directory, which will serve as the traversal root; the paths in the
second arg will be interpreted relative to that root directory.

For example, suppose your current directory is `$HOME/myproj` and you
are also working on a related project at `$HOME/mylib`. Then to crawl
the `src/foo` and `test/bar` directories of that project (i.e.
`$HOME/mylib/src/foo` and `$HOME/mylib/test/bar`), run:

[source,scheme]
----
(mibl-load-project "myproj" '("src/foo" "src/bar"))
----

Finally, running without any args - `(mibl-load-project)` - will crawl the
tree rooted at the current directory.

== Running mibl as a standalone executable

You can install `mibl` in your local system by running:

[source,shelll]
----
$ bazel run @mibl//deploy
----

Installation follows the link:[XDG] standard:

* the `mibl` executable will go in `$HOME/.local/bin`; put this in your `$PATH`.
* `mibl` dynamically loads (`dlopen`) file `libc_s7.so`; this will be
  installed in `$XDG_DATA_HOME/mibl`. By default, `XDG_DATA_HOME` =
  `$HOME/.local/share`.
* Scheme script files used by `mibl` will be installed in `$XDG_DATA_HOME/mibl`.

The `*load-path* of `mibl` will be configured to include:

* `.`  (current directory)
* `$PWD/.mibl`
* `$HOME/.mibl`
* `$XDG_DATA_HOME/.local/share/mibl`
* `$XDG_DATA_HOME/.local/share/mibl/s7`

Then run `$ mibl` to launch the repl.

== The mibl API

See link:docs/api.adoc[docs/api]

== Configuring mibl

At launch, `mibl` will try to read the first config file if finds by searching:

* `$PWD/.config/miblrc`
* `$HOME/.config/miblrc`

TODO: miblrc docs
