(let* ((lib '(library (name mylib_a)
               (public_name mylib)
               (preprocess (pps ppx_jane))
               (libraries core_kernel ppx_version)))
       (lib-alist (cdr lib))
       (name (assoc 'name lib-alist))
       (findlib-name (assoc 'public_name lib-alist))
       (preproc (assoc 'preprocess lib-alist))
       (libs (assoc 'libraries lib-alist))
       )
  libs)
  ;; preproc)
  ;; findlib-name)
  ;; lib-alist)
